# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('count', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Video', 'Видео'), ('Image', 'Изображение')], max_length=30)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('description', models.TextField(default=' ')),
                ('image', models.ImageField(default='', upload_to='media/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='EventCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='PlayListAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('advertisings', models.ManyToManyField(to='api.Advertising')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField(default='')),
                ('location', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='media/uploads')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
        ),
    ]
