# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(default=' ')),
                ('content', models.TextField(default=' ')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Norm', 'МОжно'), ('Danger', 'Нельзя'), ('Attention', 'Опасно')], max_length=30)),
            ],
        ),
    ]
