# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcalendar',
            name='event',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='EventCalendar',
        ),
    ]
